// Turns the JSON from tools/sweep-all.sh into src/data/sim-results.js, which the
// character pages and the developer menu read.
// Usage: node tools/sweep-export.js [dir] [careers] > src/data/sim-results.js

import fs from 'node:fs';
import { CHARACTERS } from '../src/config.js';
import { indexFrom, ratingOf, fitFrom, reach, ruin } from './sweep-report.js';

const dir = process.argv[2] ?? '/tmp/ladder-sweep';
const careers = Number(process.argv[3] ?? 30);
const round = (value) => Math.round(value * 100) / 100;
const characters = {};
for (const character of CHARACTERS) {
  const file = `${dir}/${character.id}.json`;
  if (!fs.existsSync(file)) continue;
  const results = JSON.parse(fs.readFileSync(file, 'utf8')).results;
  const { index, parts } = indexFrom(results);
  const fit = fitFrom(results);
  characters[character.id] = {
    index: round(index),
    rating: ratingOf(index),
    parts: Object.fromEntries(Object.entries(parts).map(([key, value]) => [key, round(value)])),
    fit: { track: fit.track, management: round(fit.management), expert: round(fit.expert), bestIndustry: fit.bestIndustry, worstIndustry: fit.worstIndustry },
    industries: Object.fromEntries(Object.entries(results).map(([industry, row]) => [industry, {
      reach: round(reach(row.auto)),
      management: round(reach(row.management)),
      expert: round(reach(row.expert)),
      ruin: round(ruin(row.careless ?? row.auto)),
      peak: row.auto.peak,
      fire: round(row.auto.fire),
      fireAge: row.auto.fireAge,
      burnouts: round(row.auto.burnouts),
    }])),
  };
}
console.log(`// Generated by tools/sweep-export.js from ${careers} simulated careers per character, industry and track.
// Reach is the share of careers reaching Director plus the share reaching VP; ruin is the share ending in
// breakdown or homelessness when played at a fixed nine-hour pace. Do not edit by hand.
export const SIM_RESULTS = ${JSON.stringify({ careers, characters }, null, 2)};
`);
